# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-04 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类名称')),
                ('label', models.CharField(blank=True, max_length=32, null=True, verbose_name='分类标签')),
                ('isshow', models.NullBooleanField(verbose_name='是否显示')),
                ('orderby', models.IntegerField(blank=True, null=True, verbose_name='排序字段')),
                ('isleaf', models.NullBooleanField(verbose_name='是否叶子')),
                ('parentid', models.ForeignKey(blank=True, db_column='parentid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='course.Category', verbose_name='父结点ID')),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='课程名称')),
                ('subtitle', models.CharField(max_length=200, null=True, verbose_name='课程子标题')),
                ('users', models.CharField(blank=True, max_length=500, null=True, verbose_name='适用人群')),
                ('target', models.CharField(blank=True, max_length=500, null=True, verbose_name='教学目标')),
                ('mt', models.IntegerField(verbose_name='课程大分类')),
                ('grade', models.CharField(max_length=32, verbose_name='课程等级')),
                ('serialize', models.CharField(max_length=32, null=True, verbose_name='课程连载状态')),
                ('studymodel', models.CharField(max_length=32, verbose_name='学习模式')),
                ('teachmode', models.CharField(blank=True, max_length=32, null=True, verbose_name='授课模式')),
                ('description', models.TextField(blank=True, null=True, verbose_name='课程介绍')),
                ('st', models.IntegerField(verbose_name='课程小分类')),
                ('status', models.CharField(blank=True, default='202001', max_length=32, null=True, verbose_name='课程状态')),
                ('study_num', models.IntegerField(null=True, verbose_name='学习人数')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('is_deleted', models.NullBooleanField(default=False, verbose_name='是否显示')),
            ],
            options={
                'db_table': 'course_base',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.CharField(max_length=32, verbose_name='收费规则')),
                ('valid', models.CharField(max_length=32, verbose_name='有效性')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('qq', models.CharField(blank=True, max_length=32, null=True, verbose_name='咨询QQ')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='价格')),
                ('price_old', models.FloatField(blank=True, null=True, verbose_name='原价')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='课程有效期-开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='课程有效期-结束时间')),
            ],
            options={
                'db_table': 'course_market',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoursePic',
            fields=[
                ('courseid', models.IntegerField(primary_key=True, serialize=False, verbose_name='课程ID')),
                ('pic', models.CharField(max_length=256, verbose_name='图片路径')),
            ],
            options={
                'db_table': 'course_pic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CoursePub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='课程名称')),
                ('users', models.CharField(max_length=500, verbose_name='适用人群')),
                ('mt', models.IntegerField(verbose_name='课程大分类')),
                ('st', models.IntegerField(verbose_name='课程小分类')),
                ('grade', models.CharField(max_length=32, verbose_name='课程等级')),
                ('studymodel', models.CharField(max_length=32, verbose_name='学习模式')),
                ('teachmode', models.CharField(blank=True, max_length=32, null=True, verbose_name='授课模式')),
                ('description', models.TextField(verbose_name='课程介绍')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='时间戳logstash使用')),
                ('charge', models.CharField(max_length=32, verbose_name='收费规则')),
                ('valid', models.CharField(max_length=32, verbose_name='有效性')),
                ('qq', models.CharField(blank=True, max_length=32, null=True, verbose_name='咨询QQ')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='价格')),
                ('price_old', models.FloatField(blank=True, null=True, verbose_name='原价')),
                ('expires', models.CharField(blank=True, max_length=32, null=True, verbose_name='过期时间')),
                ('start_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='课程有效期-开始时间')),
                ('end_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='课程有效期-结束时间')),
                ('pic', models.CharField(blank=True, max_length=500, null=True, verbose_name='图片路径')),
                ('teachplan', models.TextField(verbose_name='课程计划')),
                ('pub_time', models.CharField(blank=True, max_length=32, null=True, verbose_name='课程发布时间')),
            ],
            options={
                'db_table': 'course_pub',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teachplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=64, verbose_name='计划名称')),
                ('grade', models.CharField(default='1', max_length=1, verbose_name='层级')),
                ('ptype', models.CharField(blank=True, max_length=1, null=True, verbose_name='课程类型')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='章节及课时介绍')),
                ('timelength', models.FloatField(blank=True, null=True, verbose_name='时长')),
                ('courseid', models.IntegerField(verbose_name='课程ID')),
                ('orderby', models.CharField(blank=True, max_length=32, null=True, verbose_name='排序字段')),
                ('status', models.CharField(max_length=1, verbose_name='状态')),
                ('trylearn', models.NullBooleanField(verbose_name='是否试学')),
                ('parentid', models.ForeignKey(blank=True, db_column='parentid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='course.Teachplan', verbose_name='父计划ID')),
            ],
            options={
                'db_table': 'teachplan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeachplanMedia',
            fields=[
                ('teachplan_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='课程计划ID')),
                ('media_id', models.CharField(max_length=32, verbose_name='媒资文件ID')),
                ('media_fileoriginalname', models.CharField(max_length=128, verbose_name='媒资文件的原始名称')),
                ('media_url', models.CharField(max_length=256, verbose_name='媒资文件访问地址')),
                ('courseid', models.IntegerField(verbose_name='课程ID')),
            ],
            options={
                'db_table': 'teachplan_media',
                'managed': True,
            },
        ),
    ]
