# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-27 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachplanMediaPub',
            fields=[
                ('teachplan_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='课程计划ID')),
                ('media_id', models.CharField(max_length=32, verbose_name='媒资文件ID')),
                ('media_fileoriginalname', models.CharField(max_length=128, verbose_name='媒资文件的原始名称')),
                ('media_url', models.CharField(max_length=256, verbose_name='媒资文件访问地址')),
                ('courseid', models.IntegerField(verbose_name='课程ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='时间戳，供Logstash使用')),
            ],
            options={
                'db_table': 'teachplan_media_pub',
                'managed': True,
            },
        ),
    ]
