"""
Django settings for cz_study project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@#wi0%o4-&li_8i5$$%x=x=g6c1+o968yk+c5j13l6c(+o8@8z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'rest_framework_mongoengine',
    'djcelery',
    'booktest.apps.BooktestConfig',
    'cms.apps.CmsConfig',
    'ucenter.apps.UcenterConfig',
    'course.apps.CourseConfig',
    'filesystem.apps.FilesystemConfig',
    'search.apps.SearchConfig',
    'media.apps.MediaConfig',
    'learning.apps.LearningConfig',
    'order.apps.OrderConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cz_study.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cz_study.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cz_study',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': 3306,
    }
}

# 创建到mongodb的连接
from mongoengine import connect
connect('cz_study', host='127.0.0.1', port=27017)
connect('test', host='127.0.0.1', port=27017, alias='test')  # 用于MongoEngine使用测试
AUTH_USER_MODEL = 'ucenter.CzUser'

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# rest framework 相关配置信息
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'common.exceptions.standard_exception_handler',
    'DEFAULT_RENDERER_CLASSES': (
        'common.renderers.StandardJSONRender',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

# 课程发布配置
COURSE_PUBLISH = {
    # 站点Id
    'site_id': '5a751fab6abb5044e0d19ea1',
    # 课程详情模板Id
    'template_id': '5ad9a24d68db5239b8fef199',
    # CMS预览URL
    'preview_url': 'http://www.czstudy.com/cms/preview/',
    # 课程详情页URL子路径
    'page_web_path': '/course/detail/',
    # 课程详情页物理存储子路径
    'page_physical_path': '/course/detail/',
    # 课程详情数据主URL
    'data_url_pre': 'http://www.czstudy.com/api/course/courseview/',
    # 视频上传存储位置
    'media_upload_location': '/Users/apple/workspace/czStudy/video/',
    # ffmpeg调用位置
    'ffmpeg_path': '/Users/apple/software/ffmpeg4/ffmpeg',
}

# 消息队列相关配置

# CMS发布页面交换机
EX_CMS_POST_PAGE = 'ex_cms_post_page'
# CMS发布页面队列名
QUEUE_CMS_POST_PAGE = 'queue_cms_post_page_01'
# CMS发布页面路由key，此routingKey为门户站点ID
ROUTING_KEY_CMS_POST_PAGE = '5a751fab6abb5044e0d19ea1'

# 媒体视频处理队列
QUEUE_MEDIA_VIDEO_PROCESSOR = 'queue_media_video_processor'
# 媒体视频路由key
ROUTINGKEY_MEDIA_VIDEO = 'routingkey_media_video'
# 媒体处理交换机
EX_MEDIA_PROCESSTASK = 'ex_media_processor'

# 添加选课任务交换机
EX_ADD_CHOOSE_COURSE = 'ex_add_choose_course'
# 完成添加选课消息队列
QUEUE_FINISH_ADD_CHOOSE_COURSE = 'queue_finish_add_choose_course'
# 添加选课消息队列
QUEUE_ADD_CHOOSE_COURSE = 'queue_add_choose_course'
# 添加选课路由key
ROUTING_KEY_ADD_CHOOSE_COURSE_KEY = 'add_choose_course'
# 完成添加选课路由key
ROUTING_KEY_FINISH_ADD_CHOOSE_COURSE = 'finish_add_choose_course'

# JWT认证相关配置
JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=7),     # JWT过期时间
    'JWT_AUTH_HEADER_PREFIX': 'JWT',    # 请求头前缀
    'JWT_PAYLOAD_HANDLER': 'common.jwt.jwt_payload_handler',
}

# 通用数据验证正则，数量多时可考虑单独放到一个文件
REGEX_MOBILE = "^1\d{10}$"

# 第三方平台认证信息
YUNPIAN_APIKEY = 'yunpian_apikey'
