# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-15 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CzLearningCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(verbose_name='课程id')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('charge', models.CharField(max_length=32, null=True, verbose_name='收费规则')),
                ('price', models.FloatField(null=True, verbose_name='课程价格')),
                ('valid', models.CharField(max_length=32, null=True, verbose_name='收费规则')),
                ('start_time', models.DateTimeField(null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('status', models.CharField(max_length=32, null=True, verbose_name='选课状态')),
            ],
            options={
                'db_table': 'cz_learning_course',
            },
        ),
    ]
