# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-15 19:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CzOrders',
            fields=[
                ('order_number', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='订单号')),
                ('initial_price', models.FloatField(null=True, verbose_name='定价')),
                ('price', models.FloatField(null=True, verbose_name='交易价')),
                ('start_time', models.DateTimeField(null=True, verbose_name='支付起始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='支付过期时间')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('status', models.CharField(max_length=32, null=True, verbose_name='交易状态')),
                ('details', models.CharField(max_length=1000, null=True, verbose_name='订单明细')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaser', to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'db_table': 'cz_orders',
            },
        ),
        migrations.CreateModel(
            name='CzOrdersDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(unique=True, verbose_name='商品id')),
                ('item_num', models.IntegerField(verbose_name='商品数量')),
                ('item_price', models.FloatField(verbose_name='金额')),
                ('valid', models.CharField(max_length=32, verbose_name='课程有效性')),
                ('start_time', models.DateTimeField(null=True, verbose_name='课程开始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='课程结束时间')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.CzOrders')),
            ],
            options={
                'db_table': 'cz_orders_detail',
            },
        ),
        migrations.CreateModel(
            name='CzOrdersPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_number', models.CharField(max_length=32, null=True, unique=True, verbose_name='支付系统订单号')),
                ('status', models.CharField(max_length=32, verbose_name='交易状态')),
                ('pay_time', models.DateTimeField(null=True, verbose_name='支付时间')),
                ('pay_through', models.CharField(max_length=10, null=True, verbose_name='支付方式')),
                ('order_number', models.ForeignKey(db_column='order_number', max_length=32, on_delete=django.db.models.deletion.CASCADE, to='order.CzOrders', verbose_name='订单号')),
            ],
            options={
                'db_table': 'cz_orders_pay',
            },
        ),
        migrations.CreateModel(
            name='CzTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('delete_time', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('task_type', models.CharField(max_length=32, null=True, verbose_name='任务类型')),
                ('mq_exchange', models.CharField(max_length=64, null=True, verbose_name='交换机名称')),
                ('mq_routingkey', models.CharField(max_length=64, null=True, verbose_name='routing key')),
                ('request_body', models.CharField(max_length=512, null=True, verbose_name='任务请求的内容')),
                ('version', models.IntegerField(null=True, verbose_name='乐观锁版本号')),
                ('status', models.CharField(max_length=32, null=True, verbose_name='任务状态')),
                ('errormsg', models.CharField(max_length=512, null=True, verbose_name='任务错误信息')),
            ],
            options={
                'db_table': 'cz_task',
            },
        ),
        migrations.CreateModel(
            name='CzTaskHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('delete_time', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('task_type', models.CharField(max_length=32, null=True, verbose_name='任务类型')),
                ('mq_exchange', models.CharField(max_length=64, null=True, verbose_name='交换机名称')),
                ('mq_routingkey', models.CharField(max_length=64, null=True, verbose_name='routing key')),
                ('request_body', models.CharField(max_length=512, null=True, verbose_name='任务请求的内容')),
                ('version', models.IntegerField(null=True, verbose_name='乐观锁版本号')),
                ('status', models.CharField(max_length=32, null=True, verbose_name='任务状态')),
                ('errormsg', models.CharField(max_length=512, null=True, verbose_name='任务错误信息')),
            ],
            options={
                'db_table': 'cz_task_his',
            },
        ),
    ]
