SUCCESS = (True, 10000, "操作成功！")
FAIL = (False, 11111, "操作失败！")
UNAUTHENTICATED = (False, 10001, "此操作需要登陆系统！")
UNAUTHORISE = (False, 10002, "权限不足，无权操作！")
INVALID_PARAM = (False, 10003, "非法参数！")
SERVER_ERROR = (False, 99999, "抱歉，系统繁忙，请稍后重试！")

UPLOAD_FILE_REGISTER_FAIL = (False, 22001, "上传文件在系统注册失败，请刷新页面重试！")
UPLOAD_FILE_REGISTER_EXIST = (False, 22002, "上传文件在系统已存在！")
CHUNK_FILE_EXIST_CHECK = (False, 22003, "分块文件在系统已存在！")
MERGE_FILE_FAIL = (False, 22004, "合并文件失败，文件在系统已存在！")
MERGE_FILE_CHECKFAIL = (False, 22005, "合并文件校验失败！")

AUTH_USERNAME_NONE = (False, 23001, "请输入账号！")
AUTH_PASSWORD_NONE = (False, 23002, "请输入密码！")
AUTH_VERIFYCODE_NONE = (False, 23003, "请输入验证码！")
AUTH_ACCOUNT_NOTEXISTS = (False, 23004, "账号不存在！")
AUTH_CREDENTIAL_ERROR = (False, 23005, "账号或密码错误！")
AUTH_LOGIN_ERROR = (False, 23006, "登陆过程出现异常请尝试重新操作！")

CMS_ADDPAGE_EXISTSNAME = (False, 24001, "页面名称已存在！")
CMS_ADDPAGE_EXISTS = (False, 24002, "页面已存在！")
CMS_GENERATEHTML_DATAURLISNULL = (False, 24003, "从页面信息中找不到获取数据的url！")
CMS_GENERATEHTML_DATAISNULL = (False, 24004, "根据页面的数据url获取不到数据！")
CMS_GENERATEHTML_TEMPLATEISNULL = (False, 24005, "页面模板为空！")
CMS_GENERATEHTML_HTMLISNULL = (False, 24006, "生成的静态html为空！")
CMS_GENERATEHTML_SAVEHTMLERROR = (False, 24007, "保存静态html出错！")
CMS_PAGE_NOTEXISTS = (False, 24008, "页面不存在！")
CMS_COURSE_PERVIEWISNULL = (False, 24009, "预览页面为空！")

FS_UPLOADFILE_FILEISNULL = (False, 25001, "上传文件为空！")
FS_UPLOADFILE_BUSINESSISNULL = (False, 25002, "业务Id为空！")
FS_UPLOADFILE_SERVERFAIL = (False, 25003, "上传文件服务器失败！")
FS_DELETEFILE_NOTEXISTS = (False, 25004, "删除的文件不存在！")
FS_DELETEFILE_DBFAIL = (False, 25005, "删除文件信息失败！")
FS_DELETEFILE_SERVERFAIL = (False, 25006, "删除文件失败！")
FS_UPLOADFILE_METAERROR = (False, 25007, "上传文件的元信息请使用json格式！")
FS_UPLOADFILE_USERISNULL = (False, 25008, "上传文件用户为空！")

COURSE_NOTEXISTS = (False, 30001, "课程不存在")
COURSE_DENIED_DELETE = (False, 31001, "删除课程失败，只允许删除本机构的课程！")
COURSE_PUBLISH_PERVIEWISNULL = (False, 31002, "还没有进行课程预览！")
COURSE_PUBLISH_CDETAILERROR = (False, 31003, "创建课程详情页面出错！")
COURSE_PUBLISH_COURSEIDISNULL = (False, 31004, "课程Id为空！")
COURSE_PUBLISH_VIEWERROR = (False, 31005, "发布课程视图出错！")
COURSE_PUBLISH_CREATECOURSEPUB_ERROR = (False, 31006, "创建课程索引信息出错！"),
COURSE_TEACHPLAN_EXIST = (False, 31050, "课程已经绑定教学计划")
COURSE_TEACHPLAN_NOTEXISTS = (False, 31051, "课程计划不存在")
COURSE_MEDIS_URLISNULL = (False, 31101, "选择的媒资文件访问地址为空！")
COURSE_MEDIS_NAMEISNULL = (False, 31102, "选择的媒资文件名称为空！")
COURSE_MEDIA_TEACHPLAN_GRADEERROR = (False, 31104, "只允许选择第三级的课程计划关联视频！")
COURSE_PIC_NOTEXISTS = (False, 31201, "未找到课程图片！")
COURSE_PIC_UPLOAD_ERROR = (False, 31202, "课程图片上传失败！")

ORDER_ADD_ITEMISNULL = (False, 41001, "创建订单未选择课程！")
ORDER_ADD_ORDERNUMERROR = (False, 41002, "生成订单号错误！")
ORDER_ADD_GETCOURSEERROR = (False, 41003, "找不到课程信息！")
ORDER_FINISH_NOTFOUNDORDER = (False, 41004, "找不到订单信息！")
Pay_NOTFOUNDORDER = (False, 41010, "找不到要支付的订单！")
Pay_USERERROR = (False, 41011, "支付用户与订单用户不一致！")
Pay_NOTFOUNDPAY = (False, 41012, "支付记录不存在！")
COURSE_COMMENT_EXISTS = (False, 41031, "课程已评价！")

PortalView_ADDVIEWCOURSE_COURSEIDISNULL = (False, 42001, "课程id为空！")
PortalView_PUBLISH_PREVIEWCOURSE_ISNULL = (False, 42002, "预览课程视图为空！")
PortalView_PUBLISH_PREVIEWMEDIA_ISNULL = (False, 42003, "预览课程媒资视图为空！")
